---
title: "ET_data"
author: "Francesco Pupillo"
date: '2023-03-14'
output: 
  #github_document:
  md_document:
    variant: markdown_github
    toc: true
    toc_depth: 6
---
Scripts that analyze eye tracking data and count the missing cases

```{r setup, include=FALSE}
# get the packages
rm(list=ls())
library(ggplot2)
library(Rmisc)
library(dplyr)
source("helper_functions/get_fixations.R")
knitr::opts_chunk$set(include = FALSE, warning = FALSE)

# what is the time window of the fixations?
time_window<-"2000_2500"
```

First, get the data
```{r include=FALSE}
cd<-getwd()
setwd("pilot_data")
# get the participants
participants<-list.files()

# create an empty file to store all the participants' data
all_file<-vector()

# loop through participants and get the data
for (sub in participants){

  sub_n<-substr(sub, 5, 7)

  # encoding data
  data_encoding<-read.csv(paste0( sub, "/beh/", sub_n, "_encoding.csv"))

    # remove nas
  data_encoding<-data_encoding[!is.na(data_encoding$radians),]
  # add the trial n by block
  # count how many first scenario
  lists<-unique(data_encoding$list)
  n_list1<-nrow(data_encoding[data_encoding$list==lists[1],])
  n_list2<-nrow(data_encoding[data_encoding$list==lists[2],])
  
  data_encoding$trial_n_block<-c(1:n_list1, 1:n_list2)
  
  file_path<-paste0(sub, "/et/", sub, 
                             "_eye-right_last-fixation_et.csv")
  
  if (file.exists(file_path)){
  # get the data
    data_et<-read.csv(file_path)
    
    # get prediction and prediction error
    data_encoding<-get_fixations(data_encoding, data_et)
  # append to the data
  all_file<-rbind(all_file, data_encoding)
  # get the 
  
  }
}

# save the file
setwd(cd)
write.csv(all_file, paste0("output_data/ET_data_",time_window,".csv"))

```

Plot the results by prediction error

```{r echo=FALSE}
# first, summarise with within-participant error bars
dat_summary_fix_error<- summarySEwithin(all_file,
                                       measurevar = "fixation_error",
                                       withinvars = c("type" ), 
                                       idvar = "participant", 
                                       na.rm = T)

# plot it
# first, aggregate the data by participant, age group, and condition (type)
ggplot(all_file %>%
         group_by(participant, type)%>%
         dplyr::summarise(fixation_error=mean(fixation_error, na.rm=T)), 
       aes(x = type, y = fixation_error, colour = type ))+
  # Add some points, which correspond to the participants
  geom_point(alpha = 0.10, colour = "black" )+
  # add a line that connect those points by participant
  geom_line( aes(type, fixation_error,group = participant),
             size=1, alpha=0.1, stat="summary" , colour = 'black')+
  # add a summary line (mean)
  geom_point(stat="summary", size = 5, data = dat_summary_fix_error)+
  xlab("")+
  # add the within-participant confidence intervals
  geom_errorbar(aes( y = fixation_error, ymin = fixation_error - ci, 
                     ymax = fixation_error + ci),
                width = 0.40,size = 1.5, data=dat_summary_fix_error)+
  # divide the plot as a function of age group
  theme_classic()+
  #custom_param()+
  # delete the x axis text and ticks, as we have the legend
  theme(axis.text.x = element_blank(), 
        axis.ticks.x = element_blank()) 

# save the figure
ggsave(paste0("output_data/ET_data_",time_window,".jpeg"))
```
Now the number of NAs by participant
```{r echo=FALSE}
countNa<-all_file %>%
  group_by(participant) %>%
  dplyr::summarise(CountCase = n(), PercNA = sum(is.na(fixations))/n()*100)
    
# save it
write.csv(countNa, paste0("output_data/NA_by_part_", time_window, ".csv"))

# plot 
# count the number of NAs 
all_file$no_fix<-ifelse(is.na(all_file$fixation_prediction), 1, 0)

dat_summary_NA<- summarySEwithin(all_file,
                                   measurevar = "no_fix",
                                   withinvars = "trial_n_block" , 
                                   idvar = "participant")


# aggregate by participant and trial_position
data_aggr_trial_pos<-all_file %>%
  group_by( trial_n_block, participant) %>% 
  dplyr::summarise(no_fix= mean(no_fix, na.rm=T)) 

dat_summary_NA$trial_n_block<-as.numeric(dat_summary_NA$trial_n_block)


ggplot(dat_summary_NA,aes(x = trial_n_block, y = no_fix, 
                             group = 1))+
  stat_summary(fun.y="mean",geom="line", size = 1.5)+
  geom_ribbon(aes(ymin=no_fix-se, ymax=no_fix+se), alpha=0.5, colour=NA)+
  scale_x_continuous(breaks=seq(1, 100, 19))+
  theme_classic()

# save it
ggsave(paste0("output_data/plot_NA_by_trial_", time_window, ".jpeg"))
```

